application:
  name: Config Client
  profile: Cipher

spring:
  datasource:
    name: config-client-db
    username: config-client-db-user
    password: `{cipher}AQBuNNZoN8qNU94Xoc4VvQyNGiq2uqVdR914Y+dPsQbMzj2p+wZWcTOCHUsINuLL8ilWelovTfLjaXjrdlXey35EvYdgnUFZlwdBehBLYabtjQHAV4iTkbKvF1J2xcl6NeOnLVb67rC7oBSCjFnl4l9RGkvyRmWjXg4TeKPvGDLw8lkVfK6F12IQnD3LSvwIbZr4ZuZ0ygFidQ3t65zyOWYH2uaMeyBukL1VwVk3yQq4vC+DM+UtS953359Hh+z96wbJFTXizrNW46irUJKEV/u2xZQ/ZPsPt4pP1YM6NU9F6gSxWFwWR1femiaJUpoDrbzANA3FZGaMJ9uLS+cbdqH4ZiG7WEqN1UX+Nmbyxkuvuq/KVyHg7xEBiuDoloLN+2fbeh5IKrkQjqAFc8qt5JHz`
  h2:
    console:
      enabled: true

logging:
  level: warn