application:
  name: Config Client
  mode: Default

spring:
  datasource:
    name: config-client-db
    username: config-client-db-user
    password: config-client-db-password
  h2:
    console:
      enabled: true