application:
  name: Config Client Vault
  profile: Vault

spring:
  boot:
    admin:
      url: http://localhost:8888
      client:
          metadata:
            user.name: user
            user.password: secret
  h2:
    console:
      enabled: true