application:
  name: Config Client
  profile: Jasypt

spring:
  boot:
    admin:
      url: http://localhost:8888
      client:
          metadata:
            user.name: user
            user.password: secret
  datasource:
    name: config-client-db
    username: config-client-db-user
    password: ENC(HvwxN1e02LBp8W9SgFvgDCk6Fv9u7qz6k8jwelOj2GjYZE12loKZHg==) # use config-client-jasypt as jasypt.encryptor.password to decrypt
  h2:
    console:
      enabled: true
