application:
  name: Config Client
  profile: Cipher

spring:
  datasource:
    name: client-db
    username: client-user
    password: '{cipher}AQAqlybemTv/2bAgv55r9orMec/UHUQEp86pHupQLagPijM1G1T/Niqw0lGtev5JpbfRtT4GMCnkKzsl0yTc9hW3AJoZSu7mj8D7HsUAw5FMbv/kdbAGjvTkiGsrY7u8wZI6JR9FHPoBXJDlWp11sdzNMogi4XBDHrrerUsE6CM+TTFpfvOjFcpguHJqxTmfdzpEkmiBQ+SnRPCRs4vuaCSWDMNM7yz9MKafh2NnxPozHMjWllDowvV6QTgc903W9Xu5CkuiH68Cs4wddVjMe1rNT6rWJuddSCCv/JF9oD2LbU0LEW0//cd6TKxyrtcoZ+jSiyy4XkMoy6xDYCY8BoWeT+GMgF9Xd3NaXjN4BkSW41mEhS3QcqHOzcCJyyNkGAI='
  h2:
    console:
      enabled: true
  data:
    rest:
      default-media-type: application/json

logging:
  level: warn