application:
  name: Config Client
  profile: Plain

spring:
  datasource:
    name: client-db
    username: client-user
    password: client-password
  h2:
    console:
      enabled: true
  data:
    rest:
      default-media-type: application/json

logging:
  level: warn