application:
  name: Config Client Vault
  profile: Default

spring:
  h2:
    console:
      path: /admin/h2-console
  datasource: # other datasource properties must be provided by vault
    name: config-client-vault-db

# Actuator
management:
  context-path: /admin
  security:
    enabled: true