application:
  name: Config Client
  profile: Cipher

spring:
  datasource:
    name: config-client-db
    username: config-client-db-user
    password: '{cipher}AQBe58kD+eN7gNmcSm+UyP4LuIDy9gFQVt7kO6dMZIffoX9JqBvJ40iATfGmr8hSt6imBZs6bMzbudyhgmh4akrN37OF/ZkNFPj+/7ZSaz/xUq71LnAJH8Wr8hthcv7erGMA3S5bxIqeX1BhkK9RfQF1sEpTi9BEmwjjyLwcw3Rs0Io/aBpxilQboRPAYEl2tDnld/FqEfCzcfp/QpijkXCcjjQ2/pHLTj7feycGgOZCNy5+ZnEhKZ6IjHbAxSX9g1hnOf+nxqHabg6jlzEjKq49RQr5wnrpc/KrYgxmfyxpQpvAXlELkn+c6Q3Zs4aptuS0NkI6P/keCDOMPxE/lXY0vfyhFUfKD64qgUBmDD8mX8F6hieCQct7fdf+guEwFMTyHP+Zo5VKZa7uis29vYh'
  h2:
    console:
      enabled: true

logging:
  level: warn