sudo: false
language: java
jdk: oraclejdk8
branches:
  only:
    - develop
before_install:
  - echo "MAVEN_OPTS='-Xmx2048m'" > ~/.mavenrc
script: mvn -Dlogging.level.org.springframework=error -Dlogging.level.org.hibernate=error deploy cobertura:cobertur
after_success:
  - bash <(curl -s https://codecov.io/bash)