spring:
  datasource:
    name: client-db
    username: client-user
    # password is client-password
    # provide sample-password as jasypt.encryptor.password to decrypt
    password: ENC(A+eOm8o7/iYmYVrqrbpxf0eGTJywpR5f)
  h2:
    console:
      enabled: true
  application:
    name: local-client
  data:
    rest:
      default-media-type: application/json

logging:
  level: warn
