application:
  name: Spring Cloud Config
  profile: Default

spring:
  h2:
    console:
      path: /admin/h2-console
  datasource:
    name: config-client-vault-db
    username: config-client-vault-db-user

# Actuator
management:
  context-path: /admin
  security:
    enabled: true