spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dschadow/CloudSecurity
          search-paths: config-repo

security:
  basic:
    enabled: true
  user:
    name: user
    password: secret

server:
  port: 8888

logging:
  level:
    root: info