spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dschadow/CloudSecurity
          search-paths: config-repo
          default-label: develop

security:
  basic:
    enabled: true
  user:
    name: user
    password: secret

server:
  port: 8888

encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme