spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dschadow/CloudSecurity
          search-paths: config-repo
          default-label: develop

security:
  basic:
    enabled: true
  user:
    name: user
    password: secret

server:
  port: 8888

encrypt:
  key-store: # asymmetric encryption
   location: classpath:server.jks
   password: secret
   alias: configserver
   secret: secret
  #key: This1sABigSecret # symmetric encryption

logging:
  level: warn