spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dschadow/CloudSecurity
          search-paths: config-repo
          default-label: develop
server:
  port: 8888